
(defun sweyla693812 ()
  "Theme generated by Sweyla: http://sweyla.com/themes/seed/693812/"
  (interactive)
  (color-theme-install
   '(sweyla693812
     ((background-color . "#050200")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#639BD0"))))
     (font-lock-constant-face ((t (:foreground "#EBA3D2"))))
     (font-lock-builtin-face ((t (:foreground "#CCFFFF"))))
     (font-lock-function-name-face ((t (:foreground "#FFED87"))))
     (font-lock-variable-name-face ((t (:foreground "#FC3EBE"))))
     (font-lock-keyword-face ((t (:foreground "#C5E3F8"))))
     (font-lock-string-face ((t (:foreground "#F200FF"))))
     (font-lock-doc-string-face ((t (:foreground "#F200FF"))))
     (font-lock-type-face ((t (:foreground "#75CCE5"))))
     )))

(provide 'sweyla693812)
