
(defun sweyla876805 ()
  "Theme generated by Sweyla: http://sweyla.com/themes/seed/876805/"
  (interactive)
  (color-theme-install
   '(sweyla876805
     ((background-color . "#021500")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#635466"))))
     (font-lock-constant-face ((t (:foreground "#086C81"))))
     (font-lock-builtin-face ((t (:foreground "#0C2EC2"))))
     (font-lock-function-name-face ((t (:foreground "#740C9A"))))
     (font-lock-variable-name-face ((t (:foreground "#0056A7"))))
     (font-lock-keyword-face ((t (:foreground "#9E0C8A"))))
     (font-lock-string-face ((t (:foreground "#38A9B5"))))
     (font-lock-doc-string-face ((t (:foreground "#38A9B5"))))
     (font-lock-type-face ((t (:foreground "#CE7540"))))
     )))

(provide 'sweyla876805)
